### ISSUE TITLE
`winblend` is not respected on hovering signs

### ISSUE THREAD

**Issue by rosingrind** [dstein64/nvim-scrollview#114]
I'm using `sainnhe/sonokai` colorscheme with `termguicolors` and `mousemoveevent` enabled (`$TERM` is `xterm-256color` for `alacritty`). Default `winblend` == 50 hover screenshots below:

|scrollbar|cursor symbol|
|-|-|
|<img width="35" alt="Screenshot 2023-08-14 at 8 48 43 PM" src="https://github.com/dstein64/nvim-scrollview/assets/108860307/ed1d3141-551e-40ed-889e-75307c44ff72">|<img width="35" alt="Screenshot 2023-08-14 at 8 48 24 PM" src="https://github.com/dstein64/nvim-scrollview/assets/108860307/c5268666-64da-45f2-a8ff-79f448be9bf6">|

Is it possible to make signs respect `winblend` value? For example, setting `scrollview_signs_column = 0` results in signs' backgrounds visually distinguish from scrollbar's background:

|scrollbar|cursor symbol|none|
|-|-|-|
|<img width="35" alt="Screenshot 2023-08-14 at 8 58 25 PM" src="https://github.com/dstein64/nvim-scrollview/assets/108860307/3ba19a55-bd0e-4be3-a0ca-4f0117c66ac8">|<img width="35" alt="Screenshot 2023-08-14 at 9 00 48 PM" src="https://github.com/dstein64/nvim-scrollview/assets/108860307/3a4f042d-e4be-470c-b423-55db275ca1f1">|<img width="35" alt="Screenshot 2023-08-14 at 9 01 21 PM" src="https://github.com/dstein64/nvim-scrollview/assets/108860307/9a9a0378-822a-4a3c-9e47-bfa900a88bb9">|

Obviously, if it's meant to be like that - feel free to close the issue, as this is by far a design issue, not a real problem here.

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

Using latest `dstein64/nvim-scrollview` 7edc395

**Comment by dstein64** [comment]
One of the workarounds that I put in for #112 (7fa516c1bd73c0be3e4a8e6693a249fc6e85cb83) is causing the problematic behavior.

I've tried to accommodate in d2764f4d56e1a6a059dfe52e082e3a74b54dc8e5. Does that address the issue for you?

Since there are winblend issues when `termguicolors` is set, I've changed `scrollview_winblend` to experimental in that scenario and defaulted it to `0` (25b46b2dd55aa52e78e73d22f48a743eb75cced4).

**Comment by rosingrind** [comment]
Sure, I think d2764f4d56e1a6a059dfe52e082e3a74b54dc8e5 does solve the issue for me! I think it should be closed for now.
