### ISSUE TITLE
Pointer position is not adjusted when `winbar` is set

### ISSUE THREAD

**Issue by rosingrind** [dstein64/nvim-scrollview#117]
When you set any winbar, the recorded pointer position is shifted down by 1 cell:

https://github.com/dstein64/nvim-scrollview/assets/108860307/f1e1f833-9e41-45e8-9195-47aafbf6af4b

May be related to #72

**Comment by dstein64** [comment]
Fixed in 48b37bada0ac8b4dda6225f18133a3f7e9ec7352. Thanks for reporting the issue.
