### ISSUE TITLE
Signs won't go away

### ISSUE THREAD

**Issue by SingularisArt** [dstein64/nvim-scrollview#118]
Here's my setup:
```lua
require("scrollview").setup({
  excluded_filetypes = { "nerdtree" },
  signs_on_startup = {},
  diagnostics_severities = {},
})
```

But here's the output:
![screenshot](https://github.com/dstein64/nvim-scrollview/assets/57925294/68b1cba5-1934-4e79-b2ee-ff30e6f5b008)

I'm using the latest commit.

**Comment by SingularisArt** [comment]
The signs still show up even after disabling the scroll view (via the command provided). I don't have `require('scrollview.contrib.gitsigns').setup()` in my config. All I have is the setup function.

**Comment by dstein64** [comment]
> "The signs still show up even after disabling the scroll view (via the command provided)."

It sounds like the signs are coming from another plugin (assuming no bug in `:ScrollViewDisable`). If you uninstall scrollview, are the signs still shown?

**Comment by SingularisArt** [comment]
NVM. The issue was with statuscol.
