### ISSUE TITLE
Possible to support mouse dragging?

### ISSUE THREAD

**Issue by aj3423** [dstein64/nvim-scrollview#12]
Hi, when using this great plugin, I always trying to drag the bar with mouse, and then I realize it is view-only :)  Is it possible to support mouse dragging?

Thanks.

**Comment by dstein64** [comment]
@aj3423, thanks for submitting this feature request! I've thought about making the scrollbars interactive, but I've refrained from pursuing this until you mentioned it. This is merged as of PR #13.
