### ISSUE TITLE
Search sign colors

### ISSUE THREAD

**Issue by somsomers** [dstein64/nvim-scrollview#120]
Hello. 

Could you say, is there any way to make search sign more visible with lua config. Dark themes make it almost invisible in AstroNvim.

**Comment by dstein64** [comment]
Hi @somsomers. `:help scrollview-color-customization` has documentation on scrollview color customization.

For example, the following command changes the color of the search signs to match the highlight group `Title`.

```
highlight link ScrollViewSearch Title
```

Does this address the issue you're encountering?

**Comment by somsomers** [comment]
Yes, thank you a lot.

**Comment by somsomers** [comment]
Closing
