### ISSUE TITLE
nvim-scrollview not seeing diagnostics from coc.nvim

### ISSUE THREAD

**Issue by waych** [dstein64/nvim-scrollview#123]
Hi!  My setup includes coc.nvim which I use for LSP and navigating diagnostics. While I see diagnostics in `:CocList diagnostics`, I don't see any visible in the scrollview where I would expect to when enabled.  `:ScrollViewFirst diagnostics` as well as Next/Prev variants also do not see the diagnostics that Coc has.

Do you have any suggestions for how to debug further? I'm running the latest versions of each, as well as neovim build from source today.

**Comment by dstein64** [comment]
Hi @waych.

I've added a [contrib](https://github.com/dstein64/nvim-scrollview/tree/main/lua/scrollview/contrib)\* implementation for `coc.nvim`. 8a1976a8236aab930b209af3b12c1d99f6425323

The functionality is not added as a built-in, so it's not documented in the plugin [help file](https://github.com/dstein64/nvim-scrollview/blob/main/doc/scrollview.txt) and can't be enabled by modifying `scrollview_signs_on_startup`. Rather, it has to be enabled with a Lua function call.
```lua
require('scrollview.contrib.coc').setup()
```

The documentation in [coc.lua](https://github.com/dstein64/nvim-scrollview/blob/main/lua/scrollview/contrib/coc.lua) describes the configuration options.

With this update, are `coc.nvim` diagnostic signs properly displaying near the scrollbar?

\* Code in `contrib` may receive less maintenance and have less stability than non-contrib functionality. Use at your own risk.

**Comment by waych** [comment]
Yes this works great! Thanks!
