### ISSUE TITLE
Compatibility with 0.10 extmark sign

### ISSUE THREAD

**Issue by ofseed** [dstein64/nvim-scrollview#126]
After https://github.com/neovim/neovim/pull/26193 , the internal implementation of the diagnostic signs changed to the new extmark-based sign, `sign_getdefine` will no longer work for diagnostic signs.

I see the call of `sign_getdefine` is implemented by vimscript, which I am not familiar with. Refer to https://github.com/nvim-neo-tree/neo-tree.nvim/pull/1265/files .

**Comment by dstein64** [comment]
Thanks for letting me know @ofseed. I updated the code in b67dcc178ba4cac1858512e5ce2bd90e16e74c43. Does that fix the issue for you?

**Comment by ofseed** [comment]
Yes, thanks a lot.
