### ISSUE TITLE
Scrolling becomes very slow when Treesitter folding is enabled

### ISSUE THREAD

**Issue by UncleGravity** [dstein64/nvim-scrollview#135]
When I add the following lines to my [treesitter](https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#folding) config, scrolling becomes very very slow whenever there are more than a handful of elements on the scrollbar.  

```lua
vim.wo.foldmethod = 'expr'
vim.wo.foldexpr = 'v:lua.vim.treesitter.foldexpr()'
```

In my case adding leading spaces to 10 or 20 elements on a new document is sufficient to trigger the issue.

```
1 
2 
3 
4 
5 
6 
7 
8 
9 
0 
1 
2 
3 
4 
5 
6 
7 
8 
9 
0 
```

I also reproduced it on a fresh install of kickstart.nvim (straight from the repo, only added `nvim-scrollview` and modified the `treesitter` config) with the latest nvim nightly.

This is my nvim-scrollview config:
```lua
{
  'dstein64/nvim-scrollview',
  config = function()
    require('scrollview').setup {
      excluded_filetypes = { 'neo-tree', 'trouble' },
      current_only = true,
      always_show = true,
      base = 'right',
      hover = false,
      signs_on_startup = {
        'changelist',
        'conflicts',
        'cursor',
        'diagnostics',
        'folds',
        'latestchange',
        'loclist',
        'marks',
        'quickfix',
        'search',
        'spell',
        'textwidth',
        'trail',
      },
    }
  end,
}
```

This is my favorite scrollbar plugin btw, thanks for the hard work.

**Comment by dstein64** [comment]
Hi @UncleGravity. The windows that the plugin creates were inheriting the `foldmethod` of the host window. Since folding is not relevant for scrollview windows, I've manually set `foldmethod=manual` (fe5eb36287a6de93be54115677b257f21b60a173, 2a0ba552442638d1746379d8b8f3ba2df7d0bdf0).

If the problem isn't resolved for you, I'll re-open this issue.

**Comment by UncleGravity** [comment]
That did it!
