### ISSUE TITLE
WhichKey recursion error on mouse drag

### ISSUE THREAD

**Issue by UncleGravity** [dstein64/nvim-scrollview#136]
When I enable nvim-scrollview, it causes [which-key](https://github.com/folke/which-key.nvim) to show some strange behavior whenever I make visual selections with the mouse.  If I drag the mouse enough times it eventually throws a recursion error:
 ```
Error detected while processing ModeChanged Autocommands for "*":
Recursion detected.
Are you manually loading which-key in a keymap?
Use `opts.triggers` instad.
Please check the docs.
```

Error disappears when I disable scrollview.

Kind of hard to describe so I made a recording.  

https://github.com/user-attachments/assets/fa79e6e8-cc6a-4db3-be4c-560ed30e669b

Tested on a fresh install of kickstart.nvim (straight from the repo, only added nvim-scrollview, no other changes) with the latest nvim nightly.

**Comment by UncleGravity** [comment]
Just realized it has no thing to do with the mouse. If you enter visual mode and press-hold "j" or "k" the error shows up as well.  Seems like I'm not the only one experiencing this:

https://github.com/folke/which-key.nvim/issues/809#issuecomment-2318354868

So maybe this is a which-key specific [regression](https://github.com/folke/which-key.nvim/commit/55fa07fbbd8a4c6d75399b1d1f9005d146cda22c)?

**Comment by dstein64** [comment]
Hi @UncleGravity. The plugin was causing `ModeChanged` events. I've put in updates that prevent this.

Let me know if the problem isn't resolved for you and I'll re-open this issue.
