### ISSUE TITLE
Allow `scrollview_column == 0`

### ISSUE THREAD

**Issue by ofseed** [dstein64/nvim-scrollview#137]
Currently, scrollview only allows `scrollview_column >= 1`, this is indeed necessary for general windows, but for floating windows, it is better to allow column=0, because this way the scorllview can be displayed on the border of the floating window, reducing the display area occupied,

Like what `nvim-cmp` does:

![image](https://github.com/user-attachments/assets/1c65e736-6d4e-4750-9af0-9441a81c5ceb)

**Comment by dstein64** [comment]
Hi @ofseed, I've added a new option, `scrollview_consider_border`. When set to `v:true`, scrollbar and sign positioning will consider a floating window's border. With that and `scrollview_column` set to 1, the scrollbars and signs can be placed in a border column.

Vimscript:

```vim
let g:scrollview_consider_border = v:true
```

Lua:

```lua
vim.g.scrollview_consider_border = true

-- Or with a setup function:
require('scrollview').setup({
  ...
  consider_border = true,
  ...
})
```

**Comment by ofseed** [comment]
This is very useful, thank you very much!
