### ISSUE TITLE
Failed to install it with Plug

### ISSUE THREAD

**Issue by Ploppz** [dstein64/nvim-scrollview#2]
I added to nvim.init:
```
Plug 'dstein64/nvim-scrollview'
```

When I call `:PlugInstall` I get:
```
x nvim-scrollview:
    error: pathspec 'master' did not match any file(s) known to git
```

Edit: neovim 0.4.4. Sorry, that's probably the reason then

**Comment by michaelb** [comment]
It's not due to your old version of neovim @Ploppz , though it will not work if you don't have 0.5.
See my issue #3
