### ISSUE TITLE
fixup statusline issue for nvim-scrollview

### ISSUE THREAD

**Issue by ttys3** [dstein64/nvim-scrollview#33]
the `statusline` will looks buggy when I switch from `normal` to `insert` or other modes

tried use `au filetype scrollview setlocal laststatus=0` but not work

![image](https://user-images.githubusercontent.com/41882455/112711342-93f5d400-8f02-11eb-93a3-7677b873af5f.png)

**Comment by dstein64** [comment]
Thanks for reporting this @ttys3!

I haven't encountered this issue. Do you have a minimal set of steps I can use to reproduce the problem?

**Comment by ttys3** [comment]
Tried with minimal config, it's not `nvim-scrollview` 's problem, it is neovim's bug.

Sorry for bother

I'll fire a bug to the neovim project
