### ISSUE TITLE
Scrollview not working at all 

### ISSUE THREAD

**Issue by siduck76** [dstein64/nvim-scrollview#34]
Ive installed the plugin with packer.nvim, but I dont see any scrollbar in neovim and scrollviewRefresh doesnt work either . The startup doesnt work either :
vim.o.scrollview_on_startup = 1

I get this error 
![image](https://user-images.githubusercontent.com/59060246/114412253-8c088600-9bca-11eb-8bb1-ae6adc4bbfc4.png)

my neovim version :
![image](https://user-images.githubusercontent.com/59060246/114412414-b35f5300-9bca-11eb-98b2-83ac32293fda.png)

**Comment by dstein64** [comment]
Thanks for reporting this @siduck76!

I haven't encountered this issue. Do you have a minimal set of steps I can use to reproduce the problem?

I used the following steps on a fresh installation and `nvim-scrollview` worked as expected.

```
git clone https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
```

Create the following plugin specification in `~/.config/nvim/lua/plugins.lua`:

```
vim.cmd [[packadd packer.nvim]]
return require('packer').startup(function()
  use 'dstein64/nvim-scrollview'
end)
```

Execute the following commands:

```
:luafile ~/.config/nvim/lua/plugins.lua
:PackerCompile
:PackerInstall
```

(I selected to not remove existing directories when asked)

I then typed `:help` to load a document that would have scrollbars, and the scrollbars appeared.

Regarding `scrollview_on_startup`, that setting should be configured through `vim.g.scrollview_on_startup` as opposed to `vim.o.scrollview_on_startup` in your comment above. However, it is already set to be on by default, so would ordinarily only be used to turn it off.

**Comment by siduck76** [comment]
weird , I have it installed bu the scrollview doesnt show at all , do I need to configure anything? :(

**Comment by siduck76** [comment]
> weird , I have it installed bu the scrollview doesnt show at all , do I need to configure anything @dstein64 ? :(

**Comment by dstein64** [comment]
The scrollbars only show on documents that can be scrolled (i.e., there will be no scrollbar on short documents that can be displayed completely within the corresponding window).

If the scrollbars are not visible, it's possible that it's due to their coloring. By default, they use the same coloring that is used for visual mode selections. This can be changed with e.g., `:highlight link ScrollView Pmenu | ScrollViewRefresh`.

It's also possible that the transparency of the scrollbars are affecting their visibility. By default they use 50% transparency. This can be changed with e.g., `:let g:scrollview_winblend = 0 | ScrollViewRefresh`.

Does modifying the coloring or the transparency address the issue?

**Comment by siduck76** [comment]
highlighting it worked :) 

![image](https://user-images.githubusercontent.com/59060246/114488243-a96f3b80-9c2e-11eb-8afc-07f4f967a5f8.png)

**Comment by dstein64** [comment]
I'm glad to hear the issue is resolved!

It looks like there is not much contrast with the `Pmenu` highlight group. Here are a bunch of possible alternatives for your consideration. The full list of highlight groups can be shown with `:highlight`.

```
:highlight link ScrollView ErrorMsg | ScrollViewRefresh
:highlight link ScrollView Search | ScrollViewRefresh
:highlight link ScrollView Folded | ScrollViewRefresh
:highlight link ScrollView DiffAdd | ScrollViewRefresh
:highlight link ScrollView DiffChange | ScrollViewRefresh
:highlight link ScrollView DiffDelete | ScrollViewRefresh
:highlight link ScrollView DiffText | ScrollViewRefresh
:highlight link ScrollView SpellBad | ScrollViewRefresh
:highlight link ScrollView SpellCap | ScrollViewRefresh
:highlight link ScrollView SpellRare | ScrollViewRefresh
:highlight link ScrollView SpellLocal | ScrollViewRefresh
```

It's also possible to specify custom colors.

```
highlight ScrollView ctermbg=159 guibg=LightCyan
```

**Comment by siduck76** [comment]
Thanks @dstein64 ! is there anyway I could set a specific height for the scrollbar?  I dont want it this long 

![image](https://user-images.githubusercontent.com/59060246/114503967-bd756600-9c4b-11eb-9752-65f1e9c88918.png)

**Comment by dstein64** [comment]
> "is there anyway I could set a specific height for the scrollbar?"

@siduck76, there is no current way to set a specific height, which is dynamic. The height is relative to the height of the window, reflecting how much of the corresponding document is visible (similar to how scrollbars work in most other contexts).

**Comment by siduck76** [comment]
oh :(

**Comment by dstein64** [comment]
@ndav1d, thanks for reporting the issue!

Which version of Neovim are you using?

After loading a long document, where scrollbars would be expected, what's the output from the following command?

```vim
:echo winnr('$') | ScrollViewDisable | echo winnr('$') | ScrollViewEnable
```

If the two numbers differ, then the scrollbars are loaded but not visible.

Are scrollbars shown after executing the following command?

```vim
:let g:scrollview_character = 'x' | ScrollViewRefresh
```

If so, then there is seemingly an issue with the coloring. Does the scrollbar appear if you specify colors directly (after first disabling the scrollview character from the prior command, with `:let g:scrollview_character = 'x'`), as opposed to linking to an existing group?

```vim
highlight ScrollView ctermbg=Blue guibg=Blue
```

**Comment by ndav1d** [comment]
@dstein64 
The output of
```vim
:echo winnr('$') | ScrollViewDisable | echo winnr('$') | ScrollViewEnable
```
was `3 2`
