### ISSUE TITLE
Show scrollbar is interactive?

### ISSUE THREAD

**Issue by LeeWannacott** [dstein64/nvim-scrollview#36]
I like how Scrollbars can be dragged with the mouse :+1: 
Would it be possible to change the mouse pointer on hover to show it is interactive?
Like in CSS you can do `style.cursor = "pointer";`  on hover and `"grabbable"` when dragging.
Maybe it's a personal preference thing :man_shrugging: 

Thanks for the plugin. :100:

**Comment by dstein64** [comment]
Thanks @LeeWannacott!

I'm not sure how something like this could be implemented. Please let me know if you're aware of any other places in Vim or Neovim where the mouse pointer changes its appearance on hover; that could be helpful for seeing how such functionality could be adapted to `nvim-scrollview`.

The only scenario in the terminal where I can recall the pointer changing appearance is for [hyperlinks](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda). I don't know of a general way to have some arbitrary section of the screen correspond to a different mouse pointer, and I'm not sure if such functionality could be utilized by Neovim.

**Comment by LeeWannacott** [comment]
It's okay I'm not sure it's that great of an idea to change it, or it's really that important of an issue; hence why I closed the issue.

In VSCode they change the mouse pointer when you hover on tabs (You can click tabs in vim if you enable mouse support; but they don't change mouse pointer) interestingly they don't change mouse pointer for the scrollbar in VSCode; however they do a slight highlight when you hover and also while dragging. Maybe a slight shade/color change is easier to implement?

Either way not a big deal. Thanks.

**Comment by dstein64** [comment]
> "Maybe a slight shade/color change is easier to implement?"

As far as I know, Vim and Neovim only provide plugins with mouse coordinates corresponding to mouse click events, as opposed to providing mouse coordinates generally (i.e., when there are no clicks), so color changes may not be possible or more difficult to implement. This would also complicate changing the mouse pointer, but I thought maybe there could be some way to have the terminal application handle this if it were possible for the plugin to signal to the terminal which parts of the screen are clickable (e.g., via some escape code sequence, similarly to [hyperlinks](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda)).

**Comment by LeeWannacott** [comment]
I was talking about coloring/highlighting the scroll bar on drag not the mouse pointer (I didn't word it very well) . For example have a boolean value if it is being dragged color it using `highlight ScrollView ctermbg=159 guibg=LightCyan`. I'm not sure about your questions; I don't know vim that well. I'll do some research.

**Comment by dstein64** [comment]
> "As far as I know, Vim and Neovim only provide plugins with mouse coordinates corresponding to mouse click events, as opposed to providing mouse coordinates generally (i.e., when there are no clicks)"
(from my last comment)

The discussion at https://github.com/vim/vim/issues/8140 suggests that Vim is able to report mouse positions when running in a terminal, even without clicking. However, I don't believe that same functionality is available in Neovim.

**Comment by dstein64** [comment]
> "I'm not sure how something like this could be implemented."

This could be implemented using the functionality added to Neovim in [PR #19481](﻿﻿https://github.com/neovim/neovim/pull/19481).

**Comment by dstein64** [comment]
I'll re-open this since it now seems possible.

**Comment by dstein64** [comment]
This is implemented in e8a92cf4952c35644ae420d3ba1f04c609db303c. Hovering over signs or scrollbars will change their highlight color.

The functionality requires that `'mousemoveevent'` is set.

**Vimscript**
```vim
set mousemoveevent
```

**Lua**
```lua
vim.o.mousemoveevent = true
```
