### ISSUE TITLE
Make to scroll character customizable

### ISSUE THREAD

**Issue by JoseConseco** [dstein64/nvim-scrollview#38]
I would like to make it more modern and replace  default  '█', character with eg `|' to get more modern look:
![image](https://user-images.githubusercontent.com/13521338/116442165-7940b300-a852-11eb-953f-a28a297a471c.png)
People using patched fonts could use more fancy characters...
exposing this parameter for customization would be great.

**Comment by dstein64** [comment]
@JoseConseco, thanks for submitting this feature request!

> "...and replace default '█', character..."

`nvim-scrollview` did not have a default block character, but was rather showing a floating window with an empty buffer.

I've added functionality in 4cae22a1db7ae4ebb0eb5c3695ab3ea2cf445c11 for displaying a custom character on top of the scrollbar, set with `g:scrollview_character`. However, scrollbar transparency is not possible when this is used.

The effect shown in your screenshot can now be achieved by configuring a narrow block character for `g:scrollview_character` and configuring the scrollbar to use the `Normal` highlighting group (or some other highlighting group, presumably with the background matching what's used for `Normal`).

```
let g:scrollview_character = '▎'
highlight link ScrollView Normal
```

![scrollview_character](https://user-images.githubusercontent.com/541289/116482804-e3a62300-a853-11eb-98db-9196f457ffed.png)
