### ISSUE TITLE
Scrollbar on fixed column

### ISSUE THREAD

**Issue by YodaEmbedding** [dstein64/nvim-scrollview#4]
Is it possible to configure the scrollbar to always appear on a fixed column, e.g. at 80 characters?

This should occur regardless of how wide the window is.

**Comment by dstein64** [comment]
@YodaEmbedding, thanks for the idea!

This is now implemented (23fdffb23a3737dfdca47e18ba324c2f57f80d87).

After updating the plugin, the `g:scrollview_base` and `g:scrollview_column` variables can be used to control the scrollbar placement. The base specifies where the scrollbar is anchored. This can be `'left'`, `'right'`, or `'buffer'`. `'left'` and `'right'` anchor the scrollbar at the corresponding window edge (`'right'` is the default value). `'buffer'` anchors the scrollbar to the buffer. `g:scrollview_column` specifies the position (1-indexed) relative to the base.

The following settings correspond to the example you gave ("scrollbar to always appear on a fixed column, e.g. at 80 characters").

```
let g:scrollview_base = 'buffer'  " or 'left' to position relative to window edge
let g:scrollview_column = 80
```

**Comment by YodaEmbedding** [comment]
Using `g:` makes it difficult to set per-buffer. For example, imagine a vim help window (80 columns) and a python file (79 columns) open in two split windows. Perhaps better is `b:` so that users can set per filetype:

```vim
autocmd FileType python let b:scrollview_column=79 | let g:scrollview_base = 'buffer'
autocmd FileType rust   let b:scrollview_column=80 | let g:scrollview_base = 'buffer'
```

----

An alternative method of configuration to consider is to depend on the `colorcolumn`:

```vim
let g:scrollview_column = 'colorcolumn'  "  default
```

...though with multi-colorcolumns, the correct choice is undefined -- and requires manual control with `b:scrollview_column`.

**Comment by dstein64** [comment]
@YodaEmbedding, thanks again! I hadn't considered that.

It's now possible to configure `scrollview`'s settings specifically per-window, per-tab, and/or per-buffer, in addition to globally.

For example, `let w:scrollview_base = 'buffer'` would apply only for the window it's defined in. `let b:scrollview_base = 'left'' would apply only for the buffer.

98bd3e5f83396db0d1d392ab8ce05d3f283ecd5c
