### ISSUE TITLE
Latest code causes error on startup

### ISSUE THREAD

**Issue by aj3423** [dstein64/nvim-scrollview#41]
Just updated to the latest version, it shows error on every launch.

![err](https://user-images.githubusercontent.com/4710875/125162548-1d33cc80-e1bb-11eb-8a22-e4457adc12eb.png)

And when install with *vim-plug*, the tip from the installation section is ` Plug 'dstein64/nvim-scrollview'` which doesn't work, only works with `Plug 'dstein64/nvim-scrollview', { 'branch': 'main' }`, maybe should be updated in README.

**Comment by dstein64** [comment]
Thanks for reporting this!

Which version of Neovim are you using (e.g., `v0.5.0-dev+1312-gd2be261e8`, `v0.5.0`)? If you're using a pre-release of 0.5, or building from source, a version from after neovim/neovim#13988, merged February 22, should be sufficient to avoid those errors. The release of `v0.5.0` was on July 2.

> "And when install with vim-plug, the tip from the installation section is..."

The `vim-plug` example in the README currently includes `{ 'branch': 'main' }`:

```
Plug 'dstein64/nvim-scrollview', { 'branch': 'main' }
```

The branch specification was added last December in response to Issue #3.

**Comment by aj3423** [comment]
Indeed, my version was v0.5.0-dev+1079-g8becdec39, after upgrade to nightly nvim 0.6.0, there is no more error. 

But there comes a new problem, I defined `hi! link ScrollView TabLineSel` in vimrc to change the color, seems it doesn't work with the new version. It works if I type this command after vim launches, but how to change it in vimrc?

And please forget the README problem, I was looking for the wrong section, I should use the `vim-plug` section.

**Comment by dstein64** [comment]
What does `:verbose highlight ScrollView` show when executed after you start Neovim (prior to manually setting the color)?

This should indicate whether the color is set properly where you'd expect, and indicate whether it's being clobbered elsewhere. For example, here's what it shows for me after I tried to reproduce the issue you're encountering:

```vim                                                            
ScrollView     xxx links to TabLineSel
        Last set from ~/.config/nvim/init.vim line 1
```

This matches expectations, and the updated color works as expected.

**Comment by dstein64** [comment]
Are you setting a color scheme?

I see that the code for color schemes calls `:highlight clear`, which would reset any manually configured color settings.

If this is what's causing the issue for you, one workaround would be to make the call to `:highlight link ScrollView ...` in your configuration after `:colorscheme ...`. If that's not possible, configuring an autocommand to set colors after loading a color scheme could be a possible workaround.
```vim
autocmd ColorScheme * :highlight link ScrollView TabLineSel
```

**Comment by aj3423** [comment]
That's it, it should be put after the `:colorscheme ...` and `:set background ...`,  both of them will clear the highlight. Now I use the autocmd, also works fine.

Thanks.
