### ISSUE TITLE
disable in nvim-tree

### ISSUE THREAD

**Issue by delfick** [dstein64/nvim-scrollview#42]
Hello,

How would I go about making it so this doesn't show inside a https://github.com/kyazdani42/nvim-tree.lua pane?

**Comment by dstein64** [comment]
Scrollbars can be disabled for `nvim-tree.lua` by configuring `scrollview_excluded_filetypes` to include `NvimTree`.

For example, in VimScript:

```vim
let g:scrollview_excluded_filetypes = ['NvimTree']
```

In Lua:

```lua
vim.g.scrollview_excluded_filetypes = {'NvimTree'}
```

**Comment by delfick** [comment]
perfect, thanks!
