### ISSUE TITLE
Error after doing a :PlugUpdate

### ISSUE THREAD

**Issue by hrqmonteiro** [dstein64/nvim-scrollview#5]
Hi, today i did my usual :PlugUdpate, and after that, scrollview is returning an error when i open nvim:

```
Error detected while processing /home/hrq/.config/nvim/plugged/nvim-scrollview/plugin/scrollview.vim:
line  136:
E171: Missing :endif
Press ENTER or type command to continue
```

And this is strange cause i looked into the `scrollview.vim` file and there **is** a endif on that line..
Anyway, i wasn't able to fix it.

**Comment by dstein64** [comment]
Thanks for reporting this @hrqmonteiro!

I checked that all the `if`s are paired with a corresponding `endif` and didn't find any issue.

Are you able to properly install `nvim-scrollview` if you first remove it (i.e., install again, as opposed to update)?

**Comment by hrqmonteiro** [comment]
No, i can't. I just did that. I am getting the same error.

**Comment by dstein64** [comment]
What's the full version of `neovim` that you are you using (`:version` or `nvim --version`)?

**Comment by hrqmonteiro** [comment]
```
NVIM v0.5.0-dev+944-g82100a6bd
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/hrq/neovim/build/config -I/home/hrq/neovim/src -I/home/hrq/neovim/.deps/usr/include -I/usr/include -I/home/hrq/neovim/build/src/nvim/auto -I/home/hrq/neovim/build/include
Compiled by hrq@motherbase

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

Also, update, i am still unable to run it normally. I fi remove it and install the plugin again, i get the same "missing :endif" error.

The workaround i found, was to remove completely this function from the `nvim-scrollview.vim` file:

```
if s:scrollview_enabled
call s:ScrollViewEnable()
endif
```

And them in my `init.vim` i added a `autocmd VimEnter * ScrollViewEnable`. Then it works, the scrollbar appears.

But is does not answer to some setups, like the `let g:scrollview_active_only = 1` (It is appearing in all of my windows).

**Comment by timtyrrell** [comment]
@hrqmonteiro fyi, the variable name for "active" changed to "current": https://github.com/dstein64/nvim-scrollview/commit/e29497248ebb0578f1483760a092f7a6503b46ff

**Comment by dstein64** [comment]
@hrqmonteiro, I wonder if the issue is due to some interaction between `nvim-scrollview` and your configuration and/or other plugins. Does `nvim-scrollview` work if you load it without any other configuration or plugins, e.g., as follows (where the `help` page is loaded so that there is a document to receive scrollbars)?

```
$ git clone https://github.com/dstein64/nvim-scrollview.git
$ nvim -u NORC
:help motion.txt
:set runtimepath+=nvim-scrollview
:source nvim-scrollview/plugin/scrollview.vim
```
