### ISSUE TITLE
Scrollview conflict with Telescope - results are covered with box

### ISSUE THREAD

**Issue by JoseConseco** [dstein64/nvim-scrollview#53]
With scroll view I cant see the search results:
![image](https://user-images.githubusercontent.com/13521338/132985601-2f26543c-e35d-4537-8819-f04465ea46ba.png)

I'm preety sure it was working ok few day ago.
Without scrollview all works ok: 
![image](https://user-images.githubusercontent.com/13521338/132985567-517a82bb-a53a-4589-a82a-4e5be1da4aa9.png)

**Comment by dstein64** [comment]
Thanks for reporting the issue @JoseConseco!

Can you provide steps for reproducing? I tried the following and don't encounter the issue.

```vim
nvim
" Open a help window, which will show scrollbars
:help
" Open Telescope file finder, from the Telescope repo directory
:Telescope find_files
```

I used Neovim 0.5 with no `init.vim` file., along with the latest version of `nvim-scrollview` ([e4c243e](https://github.com/dstein64/nvim-scrollview/commit/e4c243ebdbe1a224016d7139169789c9ba5d6426)), the latest version of `telescope.nvim` ([978366b](https://github.com/nvim-telescope/telescope.nvim/commit/978366ba46e2306b60ef64bd9e51a6c758fe48f0)), and the latest version of `plenary.nvim` ([06266e7](https://github.com/nvim-lua/plenary.nvim/commit/06266e7bf675ba9af887fb6d1661b289fdd9bcf4)).

![issue_53_reproduce_attempt](https://user-images.githubusercontent.com/541289/132998083-3db13cc4-59c4-427f-a4ae-bc7d5ab318c3.png)

**Comment by JoseConseco** [comment]
You are right. Loading only scroll-view and telescope give no error.     My config is quite  complicated with around 100 plugs, its hard to tell what is going on. I will see If I can find the issue. Closing this for now.
