### ISSUE TITLE
creates a conflict when used with coc 

### ISSUE THREAD

**Issue by darzok0914** [dstein64/nvim-scrollview#59]
The bug seems to occur when I want to do a go to definition from one file to another

I can reproduce the bug consistently:

I use Coc for lsp features, the bug was reproduced  with neovim 0.5.1 and 0.6.0 with the latest coc 

1) I go to where the definition is 

![image](https://user-images.githubusercontent.com/72544332/144767487-f2e7dc9b-5aa4-4385-97f8-9b9b8fd40b10.png)

2) then I go to where this is used in the code (another file) 
![image](https://user-images.githubusercontent.com/72544332/144767500-8c68bdd9-53e1-40aa-a454-9ff47c1a875c.png)

3) I do gd (mapping for go to definition) and it works, it does jump to the definition
![image](https://user-images.githubusercontent.com/72544332/144767541-3e1e1b6f-cc66-4a29-b5ee-e74a1dd29047.png)

4) now in that same file, I go to the bottom of the file, as you can see it is line 755 so we cannot see the definition anymore
![image](https://user-images.githubusercontent.com/72544332/144767583-d28339d4-d189-4dae-9bc5-d8b98e1f0d7d.png)

5) I go back to the previous file where this was used in the code 
![image](https://user-images.githubusercontent.com/72544332/144767608-b0e8d219-16e8-4fa4-b701-746f3037ecd9.png)

6) I do a gd again and this time it jumps to the right file but not the right line
![image](https://user-images.githubusercontent.com/72544332/144767628-0c54ea45-3807-491e-b9fa-b77da94f839b.png)
 
as you can see it jumps to the top of the screen line 694. if I set the cursor back to the bottom of the file and try gd again and again it keeps going to the same line. However if I leave it to line 694 and then go back to the previous file and do a gd it will jump up to line 668, if I go back and to a gd it will jump to line 642 and so on until it actually finds the right location. 

the bug was not there on commit b7ca5298fd75700cc74b122654241f5ed24ecf96

I'll try to spend some time tomorrow and see if I can identify the exact commit that introduced the bug

**Comment by dstein64** [comment]
Thanks for reporting the issue @darzok0914!

This started with 46cc4b8.

To work around the issue, I've added an update in f55fefc that delays the scrollbar refreshing until after other pending asynchronous processing has occurred.
