### ISSUE TITLE
Mouse dragging feature broken.

### ISSUE THREAD

**Issue by aj3423** [dstein64/nvim-scrollview#64]
Recently I upgraded everything to the latest version, but mouse dragging doesn't make it scroll anymore.

Environment: Linux, nvim v0.6.0

**Comment by dstein64** [comment]
Thanks for reporting this @aj3423!

I'm unable to reproduce this. I tried using the same version of Neovim, v0.6.0.

What is the output of `:set mouse?`?

What is the output of `:nmap <leftmouse>`?

If another plugin is registering a mapping for `<leftmouse>`, `nvim-scrollview` will not clobber the other mapping. In that case, the mapping could be specified manually:
```vim
nmap <leftmouse> <plug>(ScrollViewLeftMouse)
```
of an alternative mouse button could be used:
```vim
nmap <rightmouse> <plug>(ScrollViewRightMouse)
```

**Comment by dstein64** [comment]
The issue may have been a result of #54, which switched the mouse handling functionality to use `getmousepos` to fix issues and shorten the code. That should have worked on `v0.6.0`, but not if you were on a pre-release prior to https://github.com/neovim/neovim/pull/14937 being merged.
