### ISSUE TITLE
Scrollbar shows as modified buffer

### ISSUE THREAD

**Issue by cseickel** [dstein64/nvim-scrollview#66]
This issue has two symptoms. One is that I can no longer close with my usual `:qa` command because I get this error:

```
E37: No write since last change
E162: No write since last change for buffer "[No Name]"
```

I am sure I can write my own function to close floating windows first then do a normal `:qa` if I really needed to. The bigger issue for me is that I have my tabline configured to show an "unsaved changes" marker in the tabs when any window in a tab is modified. This now always shows when a scrollbar is active which ruins a critical part of my workflow. Now I can no longer use my favorite `:wa` mapping which I really can't live without, and I never know if there is really an unsaved file or it's just the scrollbar.

I think there are buffer options to prevent it from ever showing as modified. Has this been attempted? I would be willing to submit a PR to fix this unless you have already tried and determined that it won't work.

**Comment by dstein64** [comment]
Thanks for reporting this @cseickel!

> "I think there are buffer options to prevent it from ever showing as modified. Has this been attempted?"

The plugin currently sets `buftype=nofile` and `nomodifiable`, which in the case of other windows is sufficient for showing them as non-modified e.g., in the status line.

Do you know a minimal set of steps for reproducing the issue?

**Comment by cseickel** [comment]
Of course, it doesn't happen when you want it to! Somehow reporting an issue magically fixes it sometimes... If it doesn't happen again in the next day I'll just close the issue.

**Comment by dstein64** [comment]
> "If it doesn't happen again in the next day I'll just close the issue."

👍 Sounds good @cseickel.

In addition to setting `buftype=nofile` and `nomodifiable`, the plugin is also calling `nvim_create_buf` with `true` for its second argument. This makes the buffer a scratch buffer that is always `nomodified`.

https://github.com/dstein64/nvim-scrollview/blob/f9b4b79a20b802b46049dc9cbf19ef6493b551d4/lua/scrollview.lua#L753

**Comment by cseickel** [comment]
This is not happening any more. I was in the middle of refactoring my own plugin so maybe it was my actually code that was causing the issue.

I'll close this issue now. Thanks for your quick response and the awesome plugin!

**Comment by cseickel** [comment]
I think I figured this out, it was the session! If the scrollbar window gets saved as part of the vim session and then restored, it can lose the read only options. It probably depends on your sessionoptions.
