### ISSUE TITLE
Transition to lua-style config?

### ISSUE THREAD

**Issue by adrian5** [dstein64/nvim-scrollview#69]
I was wondering what you thought about moving the config to a `.setup()` function as customary in nvim plugins? Since there aren't many options, it should be easy enough for existing users to (be forced to) transition.

```lua
require("nvim-scrollview").setup({
  auto_mouse = true,
  base = "right",
  column = 2
})
```

I have very few plugins left that don't do this, and it feels cleaner than setting vim globals.

**Comment by dstein64** [comment]
Thanks @adrian5 for your idea/request!

I don't want to break the functionality for existing users. Additionally, the logic permits controlling the plugin at the global/window/buffer/tab level by using the corresponding variable prefix (`g:`, `w:`, `t:`, `b:`). It would presumably be complicated to implement such functionality in a way that kept the state local to the Lua plugin.

As a workaround, in a603b43cf152226de6b03919356f23f2a5a5f047 I've added a `setup` function for setting scrollview global options. This way, the plugin can be configured in a manner similar to other Neovim plugins. For example:

```lua
require('scrollview').setup({
  auto_mouse = true,
  base = 'right',
  column = 2
})
```

**Comment by adrian5** [comment]
Nice, that was quick! And yes, I hadn't considered the `g/w/t/b` granularity.

Thank you!
