### ISSUE TITLE
Option to start disabled

### ISSUE THREAD

**Issue by cbirchinger** [dstein64/nvim-scrollview#73]
When i use nvim-qt and it's GUI scrollbar i want to start NVIM with nvim-scrollview disabled.
Something like "let g:scrollview_disabled" that i could drop into ginit.vim would help here.

I've experimented with au FileType * :ScrollViewDisable (also VimEnter, WinEnter, BufEnter), but
for some reason when i launch nvim-qt [file] directly this fails. It only works when i launch
Startify and pick an entry there.

GUI commands are also not initialized this early in init.vim, so it's also not easy to simply not
load the "Plug" when a GUI is being used.

**Comment by dstein64** [comment]
Hi @cbirchinger, `g:scrollview_on_startup` has the functionality you've described:

E.g.,
```vim
let g:scrollview_on_startup = 0
```
Or in Lua:
```lua
vim.g.scrollview_on_startup = 0
```

**Comment by cbirchinger** [comment]
Yes, I see, thank you. I've checked the help page but missed it.
