### ISSUE TITLE
Add search result ticks to bar

### ISSUE THREAD

**Issue by kovasap** [dstein64/nvim-scrollview#74]
In chrome, when you search for something using "ctrl-f", yellow ticks appear showing where the search results lie on the page.  It would be cool if this scrollbar showed the same for "/" search results.

![image](https://user-images.githubusercontent.com/8763010/179576437-c3e1b940-b0e5-4f95-badb-dd9ee25ae063.png)

**Comment by dstein64** [comment]
This is added PR #85.

**Comment by kovasap** [comment]
Looks great, thanks!!
