### ISSUE TITLE
With 'winwidth' set the plugin automatically applies the settings to forced window width windows

### ISSUE THREAD

**Issue by pure-bliss** [dstein64/nvim-scrollview#76]
I noticed this behavior when opening nvim-tree buffers or fugitive blame buffers. I use `winwidth=130`, and while the scrollview is enabled, the newly opened windows automatically take the 130 width instead of the much smaller ones its should take. This video should make my not so good explanation clear:

https://user-images.githubusercontent.com/83361786/188432772-d5683a06-e046-4f6a-a585-e2ec3a30992a.mp4

I recreated this with `nvim -u ~/mini.lua plugin/scrollview.vim`. 

<details>
  <summary>mini.lua</summary>

```lua
local Plug = vim.fn['plug#']
vim.call('plug#begin', '/tmp/')
Plug('dstein64/nvim-scrollview')
Plug('kyazdani42/nvim-tree.lua')
vim.call('plug#end')

require('scrollview').setup({
    excluded_filetypes = { 'NvimTree' },
    current_only = true
})

require("nvim-tree").setup {
    view = {
        adaptive_size = true,
        preserve_window_proportions = true
    }
}

-----------------------------------------------
-- CUSTOM
-----------------------------------------------

vim.opt.winwidth=130
```
</details>

**Comment by dstein64** [comment]
Thanks for reporting the issue @pure-bliss!

I've updated the code in 7847c4b3ff0912457d0c794aef86529afbc8654e to restore the window size after processing. Does this solve the issue for you?

**Comment by pure-bliss** [comment]
Hi! Thanks for the quick reply, and fix. I tried again, and couldn't reproduce the bug with the recent modifications, everything works fine now. Thanks again!
