### ISSUE TITLE
Window size breaks upon closing a vertical split

### ISSUE THREAD

**Issue by VimEnjoyer** [dstein64/nvim-scrollview#77]
I decided to update my vim plugins yesterday and I have encountered a bug
If you open neovim, open a vertical split, and close it - the height of neovim will shrink
demonstration: https://asciinema.org/a/2XDr4B9UopO9YZ328ldfyk6Jl

Does not happen if I start neovim with -u NONE or with the plugin uninstalled

Reverting this patch fixes the issue entirely: https://github.com/dstein64/nvim-scrollview/commit/7fbcc602627d30122560f4eaecf6851a3ecb173a

**Comment by dstein64** [comment]
I've updated the code in d03d1e305306b8b6927d63182384be0831fa3831 to use a version of `winrestcmd` that ignores floating windows.
