### ISSUE TITLE
Scrollview doesn't work with neovim mouse popup

### ISSUE THREAD

**Issue by Racle** [dstein64/nvim-scrollview#78]
After right clicking neovim shows mouse menu:
![image](https://user-images.githubusercontent.com/759091/191203930-084db492-9d7a-42f1-a5f0-12d59670dfdf.png)

If I have `nvim-scrollview` enabled I cannot press that menu with mouse.
I can only select with `j/k` or `arrow up/down`.

Test neovim config:
```
call plug#begin(stdpath('data') . '/plugged')
  Plug 'dstein64/nvim-scrollview', { 'branch': 'main' }
call plug#end()
```
Neovim version:
```
NVIM v0.8.0-dev
```

**Comment by dstein64** [comment]
Hi @Racle, thanks for reporting the issue!

I built Neovim from source using the latest commit. When I load the editor, then right click, I see the same menu from the image you posted above. I'm able to click the menu items with the mouse, and they work as expected with or without `nvim-scrollview`.

Do you have a minimal config and set of steps I can use for reproducing the issue?

**Comment by Racle** [comment]
> I built Neovim from source using the latest commit. 

I was using ubuntu repo for neovim updates, and it wasn't that long ago when I updated last time.

It seems that there were update and it works at intended after updating neovim.

Sorry for trouble, I'll close this now.
