### ISSUE TITLE
Character at last column is covered by scroller bar

### ISSUE THREAD

**Issue by aj3423** [dstein64/nvim-scrollview#80]
When a line is very long,  there is always a character that is covered by the scroller
![Peek 2022-11-03 21-19](https://user-images.githubusercontent.com/4710875/199731938-ba451ee0-1df7-4385-918e-54877656940c.gif)
Is it possible to not draw the scroller at current line? So that character would be visible. Or maybe even skip rendering scroller for all lines that exceed the last column?

**Comment by dstein64** [comment]
Hi @aj3423, the scrollbars are intended to be partially transparent.

Does modifying `g:scrollview_winblend` help? It's set to 50 by default, and controls the transparency level.

The values can be set between 0 and 100.

For example:

```vim
:let g:scrollview_winblend = 100
```

**Comment by aj3423** [comment]
@dstein64 Thanks, it works, with some Neovide specific params:
```
	vim.g.scrollview_winblend = 70
	vim.g.neovide_window_floating_opacity = 0
	vim.g.neovide_floating_blur = 0
	vim.g.neovide_window_floating_blur = 0
```

**Comment by Andrew15-5** [comment]
Setting `vim.g.scrollview_winblend_gui = 50` fixed the problem for me.
