### ISSUE TITLE
Exclude select mode from mappings

### ISSUE THREAD

**Issue by jemag** [dstein64/nvim-scrollview#81]
It seems that the current mappings, including  fold workarounds, are made for both `n` and `v` mode (`v` including both visual and select mode). Would it be possible to change to `x` mode so we can exclude select mode.

Currently typing `zi` during snippet, for example, will trigger the mapping, which is quite inconvenient and probably not the intent.

**Comment by dstein64** [comment]
This is fixed in 01876b4373b1764f45b4ea6036e144bef0e3721e. Thanks for letting me know and proposing the workaround!
