### ISSUE TITLE
Search sign group Incompatible with "auto-nohl" snippet

### ISSUE THREAD

**Issue by chrisgrieser** [dstein64/nvim-scrollview#88]
This is kind off more a request for support than a bug report, [but since a bunch of people have such a "auto-nohl" snippet](https://www.reddit.com/r/neovim/comments/zc720y/comment/iyvcdf0/?context=3), it is probably relevant to more people than just me

So I use the following snippet to automatically set `:nohl` when I am using a non-search key (not `n` / `N` etc.) and automatically enable search highlights when I do a search:

```lua
vim.on_key(function(char)
	local searchKeys = { "n", "N", "*", "#" }
	local searchConfirmed = (fn.keytrans(char) == "<CR>" and fn.getcmdtype():find("[/?]") ~= nil)
	if not (searchConfirmed or fn.mode() == "n") then return end
	local searchKeyUsed = searchConfirmed or (vim.tbl_contains(searchKeys, fn.keytrans(char)))
	if vim.opt.hlsearch:get() ~= searchKeyUsed then vim.opt.hlsearch = searchKeyUsed end
end, vim.api.nvim_create_namespace("auto_nohl"))
```

however, when I have nvim-scrollview as well as that snippet active, pressing `n` results in the highlights (and the search signs in the scrollbar) briefly appearing and than disappearing. I would guess it is because nvim-scrollview presses some key behind the scenes somewhere?

Would it be possible to make this plugin compatible with the auto-nohl snippet or give some advice on how the snippet has to be changed to work together with this plugin?

**Comment by chrisgrieser** [comment]
yes, the issue also occurs with nothing but nvim-scrollview and the snippet in my config :/

**Comment by dstein64** [comment]
I can now reproduce. I was originally only looking at the scrollbar signs, which still are displayed for me. But I can now see that the search pattern is not highlighted.

**Comment by dstein64** [comment]
`nvim-scrollview` calls `normal!` while updating scrollbars, which triggers the `vim.on_key` callback.

I've added a global variable, `vim.g.scrollview_refreshing`, that gets set to `v:true` while scrollbars are being refreshed (a0ae5f9, 02d0880).

With that update, a workaround is to ignore keys while scrollview is refreshing.

```lua
vim.on_key(function(char)
    if vim.g.scrollview_refreshing then return end
    ...
```

**Comment by chrisgrieser** [comment]
thanks! can confirm that this does fix the issue 😊
