### ISSUE TITLE
Show errors but not warnings from diagnostics

### ISSUE THREAD

**Issue by galou** [dstein64/nvim-scrollview#90]
Is it possible to show only errors from `diagnostics` and ignore warnings?

Thanks!
Gaël

**Comment by galou** [comment]
I looks that the solution was in the documentation:
```lua
  diagnostics_warn_symbol = '',
  diagnostics_info_symbol = '',
  diagnostics_hint_symbol = '',
```

**Comment by dstein64** [comment]
For the diagnostic signs, the default highlighting has the same background color as the editor. So by using no symbol, it appeared that no sign was being generated.

To fully enable/disable specific diagnostic severities, I [added](4add0a1bb416d349e2f6976eecb6a96bde2511a1) a configuration variable, `scrollview_diagnostics_severities`, a list of the severities for which signs should be shown.

To enable just error signs, here is the corresponding VimScript and Lua configuration code.

```vim
" VimScript
let g:scrollview_diagnostics_severities = [luaeval('vim.diagnostic.severity.ERROR')]
```

```lua
-- Lua version 1 (config variable)
vim.g.scrollview_diagnostics_severities = {vim.diagnostic.severity.ERROR}

-- Lua version 2 (as part of setup)
require('scrollview').setup({
  ...
  diagnostics_severities = {vim.diagnostic.severity.ERROR}
})
```

In all cases, this must be set up before the plugin is loaded (i.e., in `init.vim` or `init.lua`, loaded at startup).

Thanks for reporting the issue @galou.

**Comment by galou** [comment]
Woah, this was quick and unexpected (since I never used `:ScrollViewNext`). Thanks!
