### ISSUE TITLE
To show scrollbar in float windows

### ISSUE THREAD

**Issue by vollowx** [dstein64/nvim-scrollview#91]
![image](https://github.com/dstein64/nvim-scrollview/assets/73375859/863cc37d-0961-48d1-b3c4-4813d0f79da0)

Scrollbars don't show in float windows such as Lazy, Mason or LspInfo.

I didn't find any option to control it. Is this configurable? If not, could you please add it as a feature?

**Comment by dstein64** [comment]
> "I didn't find any option to control it. Is this configurable?"

Hi @huge-pancake, it's not currently possible for scrollbars and/or signs to appear in floating windows. There's no configuration option for that functionality.

> "If not, could you please add it as a feature?"

I'll consider adding this to a future version of the plugin. If it were a simple update, I'd add it quickly, but I believe there are various assumptions throughout the code that scrollbars don't appear in floating windows.

**Comment by huge-pancake** [comment]
I see, hope things work out soon :smile_cat:

**Comment by dstein64** [comment]
I've added an experimental option, `scrollview_floating_windows`, that can be set to `v:true` to enable scrollview for floating windows.

For floating windows that use `nvim_win_set_hl_ns`, the background color of scrollview signs will be incorrect (#105).

**VimScript**

```vim
:let g:scrollview_floating_windows = v:true
```

**Lua**

```lua
-- with vim.g
vim.g.scrollview_floating_windows = true,

-- with a setup() function
require('scrollview').setup({
  ...
  floating_windows = true,
  ...
})
```
