### ISSUE TITLE
Always show the scrollbar

### ISSUE THREAD

**Issue by rockyzhang24** [dstein64/nvim-scrollview#92]
The signs that recently added are the no doubt killer feature. Thank you for your efforts.

I am wondering now how to make the scrollbar always display even if the content is less than one screen?

**Comment by dstein64** [comment]
Hi @rockyzhang24, I'm glad to hear you like the recently added signs feature.

Thanks for the idea to have scrollview always show!

I've added a configuration option, `scrollview_always_show`, which defaults to `v:false`. When set to `v:true`, scrollbars and signs will appear even when all lines are visible.

#### VimScript

```vim
let g:scrollview_always_show = v:true
```

#### Lua

```lua
-- Using a config variable:
vim.g.scrollview_always_show = true

-- Or using setup():
require('scrollview').setup({
  ...
  always_show = true,
  ...
})
```

**Comment by rockyzhang24** [comment]
Thank you so much!
