### ISSUE TITLE
Bug: `m` keymappings lag due to ScrollView keybinding

### ISSUE THREAD

**Issue by chrisgrieser** [dstein64/nvim-scrollview#93]
I have removed `m` to `%` and with this plugin installed, any usage of `m` resulted in a noticable lag.

Looking into it, it seems that this lag is created by [the `m{letter}` mappings set by this plugin](https://github.com/dstein64/nvim-scrollview/blob/b6833be937caa0784630dab32f041d7c26ed34d4/lua/scrollview/signs/marks.lua#L34). 

Essentially, that part of the code assumes that users have not remapped `m` to something other than mark-movement, which often is not the case. Furthermore, it these mappings are created, even though I do not have included "marks" in my list of signgroups for this plugin.

A potential solution might be to add conditionals for the presence of "marks" in the list of enabled signgroups, and  `m` not being remapped before the `m{letter}` keymaps are created by this plugin

**Comment by dstein64** [comment]
Thanks for debugging and reporting the issue!

There's now an option `scrollview_marks_create_mappings` that controls whether the mark mappings are created. This defaults to `v:false` when there is an existing `m` mapping.

Another workaround for lagging mappings is to add `<nowait>` (documented under `:help :map-nowait`) when generating the mapping, assuming it wouldn't be problematic if this prevents some mappings that use the same key prefix.

**Comment by chrisgrieser** [comment]
thanks, can confirm that it works!
