### ISSUE TITLE
Bug: keymaps created by plugin should should be omitted from whichkey

### ISSUE THREAD

**Issue by chrisgrieser** [dstein64/nvim-scrollview#97]
For keymaps created by this plugin, e.g. for `z{letter}`, the plugins does clutter up whichkey.nvim: 
![CleanShot 2023-06-09 at 20 56 44@2x](https://github.com/dstein64/nvim-scrollview/assets/73286100/ef8a1d0f-e001-40bd-b953-7bbc2d9b8365)

The problem should pretty easy to fix though, since the keymap just needs to use `desc = "which_key_ignore"`, see: https://github.com/folke/which-key.nvim/issues/391

**Comment by dstein64** [comment]
I just [added](https://github.com/dstein64/nvim-scrollview/commit/e7532e753c208c76d2923edfc309aadea92bcc41) an experimental config variable, `scrollview_refresh_mapping_desc`, that can be used to set the `desc` field of the plugin's refresh mappings.

For your use case, it sounds like you'd want something like the following:

#### Vimscript
```vim
let g:scrollview_refresh_mapping_desc = 'which_key_ignore'
```

#### Lua config variable
```lua
vim.g.scrollview_refresh_mapping_desc = 'which_key_ignore'
```

#### Lua `setup` call
```lua
require('scrollview').setup({
  ...
  refresh_mapping_desc = 'which_key_ignore',
  ...
})
```

**Comment by chrisgrieser** [comment]
Thanks, this works!

I'm only wondering: Is there any reason why I would want to give the refresh mappings a different description? I cannot really think of one, and in this case, there isn't really a need for configuring this by the user? 🤔

**Comment by dstein64** [comment]
Making this configurable was done for the following reasons:
1.  In case there are other similar plugins (or other similar plugins in the future) that need similar handling.
2. In case users don't want the update (I'm not a user of `which-key`, so I don't know whether that's the case).
3. As a precaution in case the `desc` field is used differently for other purposes. The documentation describes it as a "human readable description", so fixing it at "which_key_ignore" would not follow its documented purpose.
